[package]
name = "scripty"
version = "0.1.0"
authors = ["0/0 <beerights@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
json = "0.12"
songbird = "0.1"
sentry = "0.21.0"

[dependencies.serenity]
version = "0.10"
features = ["client", "standard_framework", "voice", "rustls_backend", "framework"]

[dependencies.tokio]
version = "1.0"
features = ["full"]
