[package]
name = "scripty"
version = "0.1.0"
authors = ["0/0 <beerights@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
json = "0.12"
songbird = "0.1"
sentry = "0.21.0"
toml = "0.5"
once_cell = "1.5"
chrono = "0.4"
funty = "=1.1"
systemstat = "*"
tokio-tungstenite = "*"
serde_json = "1.0"
futures-core = "*"
uuid = { version = "0.8", features = ["serde", "v4"] }
deepspeech = "0.9"
audrey = "*"
dasp_interpolate = { version = "*", features = ["linear"] }
dasp_signal = "*"
num_cpus = "1.13"

[dependencies.redis]
version = "*"
features = ["aio", "connection-manager", "tokio-comp"]

[dependencies.serenity]
version = "0.10"
features = ["client", "standard_framework", "voice", "rustls_backend", "framework", "cache", "collector"]

[dependencies.tokio]
version = "1.0"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sqlx]
version = "0.5"
features = ["runtime-tokio-rustls", "sqlite"]
